2021-02-13 16:26:14,117 ERROR <NEWS_APP_INFO> ******** Erro ao excluir not√≠cia id: 602724275fe26a121fa67608
Traceback (most recent call last):
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 267, in get
    result = next(queryset)
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1565, in __next__
    raw_doc = next(self._cursor)
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1215, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/dao/news_dao.py", line 22, in delete_news
    NewsModel.objects.get(id=id).delete()
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 270, in get
    raise queryset._document.DoesNotExist(msg)
model.news_model.DoesNotExist: NewsModel matching query does not exist.
2021-02-13 16:26:14,154 ERROR <NEWS_APP_INFO> Trace: NewsModel matching query does not exist.
Traceback (most recent call last):
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 267, in get
    result = next(queryset)
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1565, in __next__
    raw_doc = next(self._cursor)
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1215, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/dao/news_dao.py", line 22, in delete_news
    NewsModel.objects.get(id=id).delete()
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 270, in get
    raise queryset._document.DoesNotExist(msg)
model.news_model.DoesNotExist: NewsModel matching query does not exist.
2021-02-13 18:56:41,982 ERROR <NEWS_APP_INFO> asdfasdf
Traceback (most recent call last):
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 267, in get
    result = next(queryset)
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1565, in __next__
    raw_doc = next(self._cursor)
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1215, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/dao/user_dao.py", line 12, in get_user_by_email
    user_resp = UserModel.objects.get(email=email)
  File "/Users/doug/Devel/noticias-ed-globo/noticias-crud/backend/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 270, in get
    raise queryset._document.DoesNotExist(msg)
model.user_model.DoesNotExist: UserModel matching query does not exist.
